# Simplified AWS Distro for OpenTelemetry Configuration for ECS with X-Ray
extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  resource:
    attributes:
      - key: service.name
        value: "aws-otel-ecs-service"
        action: upsert

exporters:
  awsxray:
    no_verify_ssl: false
    local_mode: false
    region: us-east-1
    
  awscloudwatchmetrics:
    region: us-east-1
    namespace: AWS/ECS/ContainerInsights

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [awsxray]
    
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [awscloudwatchmetrics]
