extensions:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 30s
          static_configs:
            - targets: ['localhost:8888']

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        include_metadata: true
        keepalive:
          server_parameters:
            max_connection_age: 1m0s
            max_connection_age_grace: 5m0s
            max_connection_idle: 1m0s
            time: 2h
            timeout: 20s
        max_recv_msg_size_mib: 4
      http:
        endpoint: 0.0.0.0:4318
        include_metadata: true

processors:
  batch:
    send_batch_max_size: 1024
    send_batch_size: 512
    timeout: 1s

  memory_limiter:
    limit_mib: 512
    spike_limit_mib: 128
    check_interval: 1s

  resource:
    attributes:
      - key: deployment.environment
        value: "production"
        action: upsert

exporters:
  logging:
    loglevel: debug
  otlp/honeycomb_direct_traces:
    compression: gzip
    endpoint: ${HONEYCOMB_ENDPOINT}:443
    headers:
      x-honeycomb-team: ${HONEYCOMB_API_KEY}
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_elapsed_time: 300s
      max_interval: 30s
    sending_queue:
      enabled: true
    tls:
      insecure: false
  otlp/honeycomb_direct_metrics:
    compression: gzip
    endpoint: ${HONEYCOMB_ENDPOINT}:443
    headers:
      x-honeycomb-team: ${HONEYCOMB_API_KEY}
      x-honeycomb-dataset: otel-collector-metrics
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_elapsed_time: 300s
      max_interval: 30s
    sending_queue:
      enabled: true
    tls:
      insecure: false
  otlp/honeycomb_collector_metrics:
    compression: gzip
    endpoint: ${HONEYCOMB_ENDPOINT}:443
    headers:
      x-honeycomb-team: ${HONEYCOMB_API_KEY}
      x-honeycomb-dataset: collector-operations
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_elapsed_time: 300s
      max_interval: 30s
    sending_queue:
      enabled: true
    tls:
      insecure: false
  otlp/honeycomb_direct_logs:
    compression: gzip
    endpoint: ${HONEYCOMB_ENDPOINT}:443
    headers:
      x-honeycomb-team: ${HONEYCOMB_API_KEY}
      x-honeycomb-dataset: otel-ecs-logs
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_elapsed_time: 300s
      max_interval: 30s
    sending_queue:
      enabled: true
    tls:
      insecure: false

service:
  extensions: [pprof, zpages, health_check]
  telemetry:
    logs:
      level: debug
      development: true
      encoding: console
    metrics:
      level: detailed
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - resource
        - batch
      exporters:
        - logging
        - otlp/honeycomb_direct_traces
    metrics:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
      exporters:
        - logging
        - otlp/honeycomb_direct_metrics
    metrics/collector_operations:
      receivers:
        - prometheus
      processors:
        - batch
      exporters:
        - logging
        - otlp/honeycomb_collector_metrics
    logs:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - resource
        - batch
      exporters:
        - logging
        - otlp/honeycomb_direct_logs